package restaurante_sql.Pedido;

import Classes.Conta;
import Classes.Pedido;
import Classes.Produto;
import Classes.Usuario;
import DAO.Conexao;
import DAO.ContaDAO;
import DAO.PedidoDAO;
import DAO.ProdutoDAO;
import java.sql.Connection;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_sql.TelaInicial_Garcom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Hoope
 */
public class Excluir_Produto extends javax.swing.JFrame {

    /**
     * Creates new form Abrir_Conta
     */
    public Excluir_Produto(int idconta,Usuario u) {
        initComponents();       
        setSize(690,400);
        setLocationRelativeTo(this);
        setResizable(false);
        setTitle("Restaurante");
        this.idconta = idconta;
        this.u = u;
        AtualizaTable();
    }
    
    int idconta;
    Usuario u = new Usuario();
    
    float total;
    
    public void AtualizaTable(){
        Connection con = Conexao.AbrirConexao();
        PedidoDAO sql = new PedidoDAO(con);
        List<Pedido> lista = new ArrayList<>();
        lista = sql.ConsultaUnica(this.idconta);
        
        ProdutoDAO pd = new ProdutoDAO(con);
        List<Produto> lista2 = new ArrayList<>();
        lista2 = pd.Consulta();
        
        
        
        DefaultTableModel tbm = (DefaultTableModel) Tabela.getModel();
        NumberFormat nf = NumberFormat.getCurrencyInstance();// Iniciando formatação
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(2);
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        int i = 0;
        for (Pedido tab : lista) {
            //Object object = arr[j];
            for(Produto tab2: lista2){
                if (tab2.getId() == tab.getIdproduto()) {
                
                tbm.addRow(new String[1]);
                Tabela.setValueAt(tab.getId(),i,0);
                Tabela.setValueAt(tab2.getNome(),i,1);
                Tabela.setValueAt(tab.getQtn(),i,2);
                Tabela.setValueAt(nf.format(Float.parseFloat(tab2.getValor())),i,3);
                Tabela.setValueAt(tab.getTotal(),i,4);
                
                this.total += Float.parseFloat(tab.getTotal());



                i++;
                }
            
            }
        }
    }

    private Excluir_Produto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 400));

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Excluir pedido");

        Tabela.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        Tabela.setForeground(new java.awt.Color(255, 102, 0));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Preço U.", "Total"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        int linha = Tabela.getSelectedRow();
        int id = (int) Tabela.getValueAt(linha, 0);
        float total =  Float.parseFloat((String) Tabela.getValueAt(linha, 4));
        
        int c = JOptionPane.showConfirmDialog(null,"Deseja realmente retirar este pedido da conta?","Restaurante",JOptionPane.INFORMATION_MESSAGE);
        if(c == JOptionPane.YES_OPTION){
            Connection con = Conexao.AbrirConexao();
            PedidoDAO sql = new PedidoDAO(con);
            if(sql.Deletar(id)){
                ContaDAO sql2 = new ContaDAO(con);
                Conta cc = new Conta();
                cc.setId(this.idconta);
                float t = this.total - total;
                cc.setTotal(""+t);
                if(sql2.AlterarTotal(cc)){
                    JOptionPane.showMessageDialog(null, "Pedido deletado","Restaurante",JOptionPane.INFORMATION_MESSAGE);
                    new TelaInicial_Garcom(this.u).setVisible(true);
                    dispose();
                }
            }
            
        }
    }//GEN-LAST:event_TabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Excluir_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Excluir_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Excluir_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Excluir_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Excluir_Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
