/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_sql.Pedido;

import Classes.Conta;
import Classes.Mesa;
import Classes.Pedido;
import Classes.Produto;
import Classes.Usuario;
import DAO.Conexao;
import DAO.ContaDAO;
import DAO.MesaDAO;
import DAO.PedidoDAO;
import DAO.ProdutoDAO;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import restaurante_sql.Conta.*;
import restaurante_sql.TelaInicial_Garcom;

/**
 *
 * @author Hoope
 */
public class Produto_Conta extends javax.swing.JFrame {

    /**
     * Creates new form Fechamento_Conta
     */
    public Produto_Conta(Usuario u,int idconta,int idmesa,float total) {
        initComponents();
        setSize(690,400);
        setLocationRelativeTo(this);
        setResizable(false);
        setTitle("Restaurante");
        AtualizaProduto();
        this.u = u;
        this.idmesa = ""+idmesa;
        this.idconta = ""+idconta;
        this.total = total;
    }
    
    Usuario u = new Usuario();
    
    List<Produto> pro = new ArrayList<>();
    
    String idmesa = "";
    String idconta = "";
    float total;
    
    String id = "";
    String valor = "";

    private Produto_Conta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void AtualizaProduto(){
        Connection con = Conexao.AbrirConexao();
        ProdutoDAO sql = new ProdutoDAO(con);
        List<Produto> lista = new ArrayList<>();
        lista = sql.ConsultaPro();
        this.pro = lista;
       
        
        for (Produto tab:lista){
            
            JcbProduto.addItem(tab.getNome());

            
        }
        
//        System.out.println("R$:"+nf.format(total));
        //Valor.setText(nf.format(total));
        Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JcbProduto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JcbQuantidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 400));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Adicionar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo-de-Restaurante-min.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Adicionar pedido");

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Produto:");

        JcbProduto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        JcbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um produto" }));
        JcbProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbProdutoItemStateChanged(evt);
            }
        });
        JcbProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JcbProdutoFocusLost(evt);
            }
        });
        JcbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JcbProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JcbProdutoMouseEntered(evt);
            }
        });
        JcbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbProdutoActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Quantidade:");

        JcbQuantidade.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        JcbQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(233, 233, 233))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton1)))
                .addGap(0, 206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JcbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbProdutoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_JcbProdutoItemStateChanged

    private void JcbProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbProdutoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_JcbProdutoFocusLost

    private void JcbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcbProdutoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JcbProdutoMouseClicked

    private void JcbProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcbProdutoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_JcbProdutoMouseEntered

    private void JcbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbProdutoActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String id = null;
        String valor = null;

        for (Produto tab:this.pro){
            if(tab.getNome() == JcbProduto.getSelectedItem()){
                i = 1; id = tab.getId()+""; valor = tab.getValor();
            }else{

            }
        }
        if(i == 1){
            this.id = id+"";
            this.valor = valor+"";
//            System.out.println("Mesa: "+this.idmesa);
//            System.out.println("Valor U.: "+this.valor);
//            System.out.println("Id Pro.: "+this.id);
        }else{
            this.id = "";
            this.valor = "";
        }

    }//GEN-LAST:event_JcbProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = Conexao.AbrirConexao();
        ContaDAO contadao = new ContaDAO(con);
       
        
        if(!this.id.equals("") && !this.valor.equals("")){
            Conta c = new Conta();
            c.setId(Integer.parseInt(this.idconta));
           // c.setIdfuncionario(this.u.getId());
           
            float total = Float.parseFloat((String) JcbQuantidade.getSelectedItem())*Float.parseFloat(this.valor);
            float totalconta = total + this.total;
            c.setTotal(""+totalconta);
            
            
            if(contadao.AlterarTotal(c)){
                PedidoDAO sql = new PedidoDAO(con);
                
                Pedido p = new Pedido();
                p.setIdconta(Integer.parseInt(this.idconta));
                p.setIdproduto(Integer.parseInt(this.id));
                p.setQtn((String) JcbQuantidade.getSelectedItem());
                p.setTotal(""+total);
                
                if(sql.Cadastro(p)){
                    
                        JOptionPane.showMessageDialog(null,"Pedido adicionado" ,"Restaurante",JOptionPane.INFORMATION_MESSAGE);
                        new TelaInicial_Garcom(this.u).setVisible(true);
                        dispose();
                       
                }       
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Escolha opções válidas","Restaurante",JOptionPane.WARNING_MESSAGE);
        }
            
        
        
        
        
        
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto_Conta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbProduto;
    private javax.swing.JComboBox<String> JcbQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
