/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_sql.Conta;

import Classes.Conta;
import Classes.Mesa;
import Classes.Pedido;
import Classes.Produto;
import Classes.Usuario;
import DAO.Conexao;
import DAO.ContaDAO;
import DAO.MesaDAO;
import DAO.PedidoDAO;
import DAO.ProdutoDAO;
import DAO.UsuarioDAO;
import java.sql.Connection;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_sql.TelaInicial_Garcom;

/**
 *
 * @author Hoope
 */
public class Abrir_Conta extends javax.swing.JFrame {

    /**
     * Creates new form Abrir_Conta
     */
    public Abrir_Conta(Usuario u) {
        initComponents();
        
        setSize(690,400);
        setLocationRelativeTo(this);
        setResizable(false);
        setTitle("Restaurante");
        AtualizaMesa();
        AtualizaProduto();
        this.u = u;
    }
    Usuario u = new Usuario();
    
    List<Produto> pro = new ArrayList<>();
    
    String id = "";
    
    String valor = "";

    private Abrir_Conta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void AtualizaMesa(){
        Connection con = Conexao.AbrirConexao();
        MesaDAO sql = new MesaDAO(con);
        List<Mesa> lista = new ArrayList<>();
        lista = sql.Consulta();
       
        
        for (Mesa tab : lista) {
            JcbMesa.addItem(tab.getId()+"");
        }
        
//        System.out.println("R$:"+nf.format(total));
        //Valor.setText(nf.format(total));
        Conexao.FecharConexao(con);
    }
    
     public void AtualizaProduto(){
        Connection con = Conexao.AbrirConexao();
        ProdutoDAO sql = new ProdutoDAO(con);
        List<Produto> lista = new ArrayList<>();
        lista = sql.ConsultaPro();
        this.pro = lista;
       
        
        for (Produto tab:lista){
            
            JcbProduto.addItem(tab.getNome());

            
        }
        
//        System.out.println("R$:"+nf.format(total));
        //Valor.setText(nf.format(total));
        Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JcbMesa = new javax.swing.JComboBox<>();
        JcbProduto = new javax.swing.JComboBox<>();
        JcbQuantidade = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo-de-Restaurante-min.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Abrir conta");

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Mesa:");

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Produto:");

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Quantidade:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Abrir Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JcbMesa.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        JcbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma mesa" }));

        JcbProduto.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        JcbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um produto" }));
        JcbProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbProdutoItemStateChanged(evt);
            }
        });
        JcbProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JcbProdutoFocusLost(evt);
            }
        });
        JcbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JcbProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JcbProdutoMouseEntered(evt);
            }
        });
        JcbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbProdutoActionPerformed(evt);
            }
        });

        JcbQuantidade.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        JcbQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 102, 0));
        jButton17.setText("Tela Inicial");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton17)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JcbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(JcbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(138, 138, 138))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = Conexao.AbrirConexao();
        ContaDAO contadao = new ContaDAO(con);
        
        String mesa = (String)JcbMesa.getSelectedItem();
        
        if(!this.id.equals("") && !this.valor.equals("") && !mesa.equals("Escolha uma mesa")){
            Conta c = new Conta();
            c.setIdfuncionario(this.u.getId());
            c.setIdmesa(Integer.parseInt((String) JcbMesa.getSelectedItem()));

            Date d = new Date();
            SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat hora = new SimpleDateFormat("HH:mm");

            c.setData(data.format(d));
            c.setHora(hora.format(d));
            float total = Float.parseFloat((String) JcbQuantidade.getSelectedItem())*Float.parseFloat(this.valor);
            c.setTotal(""+total);
            c.setSituacao("Aberta");
            
            if(contadao.Cadastro(c)){
                PedidoDAO sql = new PedidoDAO(con);
                
                Pedido p = new Pedido();
                p.setIdconta(contadao.idConta(c));
                p.setIdproduto(Integer.parseInt(this.id));
                p.setQtn((String) JcbQuantidade.getSelectedItem());
                p.setTotal(""+total);
                
                if(sql.Cadastro(p)){
                    
                    Produto pro = new Produto();
                    int id = p.getIdproduto();
                    pro.setId(id);
                    
                    ProdutoDAO sqlpro = new ProdutoDAO(con);
                    List<Produto> lista = new ArrayList<>();
                    lista = sqlpro.PreAlterar(pro);
                     int estoque = 0;
                    // System.out.println(""+lista);
                    for(Produto tab : lista){
                        estoque = Integer.parseInt(tab.getEstoque())- Integer.parseInt((String) JcbQuantidade.getSelectedItem());
                       //System.out.println("asasd"+tab.getEstoque());
                        
                    }
                    pro.setEstoque(""+estoque);
                    //System.out.println(pro.getEstoque());
                    
                    if(sqlpro.AlterarEstoque(pro)){
                        MesaDAO mesaa = new MesaDAO(con);
                        Mesa m = new Mesa();
                        m.setId(Integer.parseInt(mesa));

                        if(mesaa.Alterar(m)){
                            JOptionPane.showMessageDialog(null,"Conta Aberta!" ,"Restaurante",JOptionPane.INFORMATION_MESSAGE);
                            new TelaInicial_Garcom(this.u).setVisible(true);
                            dispose();

                        }
                    
                    }   
                }       
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Escolha opções válidas","Restaurante",JOptionPane.WARNING_MESSAGE);
        }
            
        
        
        
        
        
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JcbProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbProdutoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JcbProdutoItemStateChanged

    private void JcbProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbProdutoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JcbProdutoFocusLost

    private void JcbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcbProdutoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JcbProdutoMouseClicked

    private void JcbProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcbProdutoMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JcbProdutoMouseEntered

    private void JcbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbProdutoActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String id = null;
        String valor = null;
        
        
        for (Produto tab:this.pro){
            if(tab.getNome() == JcbProduto.getSelectedItem()){
                i = 1; id = tab.getId()+""; valor = tab.getValor();
            }else{
                
            }
        }
        if(i == 1){
            this.id = id+"";
            this.valor = valor+"";
            System.out.println("Mesa: "+JcbMesa.getSelectedItem());
            System.out.println("Valor U.: "+this.valor);
            System.out.println("Id Pro.: "+this.id);
        }else{
           this.id = "";
           this.valor = ""; 
        }
        
        
    }//GEN-LAST:event_JcbProdutoActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        new TelaInicial_Garcom(u).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abrir_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abrir_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abrir_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abrir_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abrir_Conta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbMesa;
    private javax.swing.JComboBox<String> JcbProduto;
    private javax.swing.JComboBox<String> JcbQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
