/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante_sql;

import restaurante_sql.Garcom.Cadastrar_Garcom;
import restaurante_sql.Garcom.Calc_Ver_Garcom;
import restaurante_sql.Garcom.Excluir_Garcom;
import restaurante_sql.Garcom.Ver_Edi_Garcom;
import restaurante_sql.Garcom.Visualizar_Garcom;
import restaurante_sql.Mesa.Relatorio_Mesa;
import restaurante_sql.Produto.Cadastrar_Produto;
import restaurante_sql.Produto.Excluir_Produto;
import restaurante_sql.Produto.Ver_Edi_Produto;
import restaurante_sql.Produto.Visualizar_Produto;

/**
 *
 * @author Hoope
 */
public class TelaInicial_Gerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial_Gerente() {
        initComponents();
        setSize(690,400);
        setLocationRelativeTo(this);
        setResizable(false);
        setTitle("Restaurante");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JmiCadPro = new javax.swing.JMenuItem();
        JmiVisuPro = new javax.swing.JMenuItem();
        JmiEdiPro = new javax.swing.JMenuItem();
        JmiExcPro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JmiCalcComi = new javax.swing.JMenuItem();
        JmiCadGar = new javax.swing.JMenuItem();
        JmiVisuGar = new javax.swing.JMenuItem();
        JmiEdiGar = new javax.swing.JMenuItem();
        JmiExcGar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo-de-Restaurante.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Restaurante Boa Comida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("Produtos");

        JmiCadPro.setText("Cadastrar");
        JmiCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadProActionPerformed(evt);
            }
        });
        jMenu1.add(JmiCadPro);

        JmiVisuPro.setText("Visualizar");
        JmiVisuPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiVisuProActionPerformed(evt);
            }
        });
        jMenu1.add(JmiVisuPro);

        JmiEdiPro.setText("Editar");
        JmiEdiPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiEdiProActionPerformed(evt);
            }
        });
        jMenu1.add(JmiEdiPro);

        JmiExcPro.setText("Excluir");
        JmiExcPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiExcProActionPerformed(evt);
            }
        });
        jMenu1.add(JmiExcPro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Garçom");

        JmiCalcComi.setText("Calcular Comissões");
        JmiCalcComi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCalcComiActionPerformed(evt);
            }
        });
        jMenu2.add(JmiCalcComi);

        JmiCadGar.setText("Cadastrar");
        JmiCadGar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadGarActionPerformed(evt);
            }
        });
        jMenu2.add(JmiCadGar);

        JmiVisuGar.setText("Visualizar");
        JmiVisuGar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiVisuGarActionPerformed(evt);
            }
        });
        jMenu2.add(JmiVisuGar);

        JmiEdiGar.setText("Editar");
        JmiEdiGar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiEdiGarActionPerformed(evt);
            }
        });
        jMenu2.add(JmiEdiGar);

        JmiExcGar.setText("Excluir");
        JmiExcGar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiExcGarActionPerformed(evt);
            }
        });
        jMenu2.add(JmiExcGar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mesas");

        jMenuItem10.setText("Gerar relatòrio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmiVisuProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiVisuProActionPerformed
        // TODO add your handling code here:
        new Visualizar_Produto().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiVisuProActionPerformed

    private void JmiEdiProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiEdiProActionPerformed
        // TODO add your handling code here:
        new Ver_Edi_Produto().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiEdiProActionPerformed

    private void JmiCalcComiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCalcComiActionPerformed
        // TODO add your handling code here:
        new Calc_Ver_Garcom().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiCalcComiActionPerformed

    private void JmiCadGarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadGarActionPerformed
        // TODO add your handling code here:
        new Cadastrar_Garcom().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiCadGarActionPerformed

    private void JmiVisuGarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiVisuGarActionPerformed
        // TODO add your handling code here:
        new Visualizar_Garcom().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiVisuGarActionPerformed

    private void JmiEdiGarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiEdiGarActionPerformed
        // TODO add your handling code here:
        new Ver_Edi_Garcom().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiEdiGarActionPerformed

    private void JmiExcGarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiExcGarActionPerformed
        // TODO add your handling code here:
        new Excluir_Garcom().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiExcGarActionPerformed

    private void JmiCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadProActionPerformed
        // TODO add your handling code here:
        new Cadastrar_Produto().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiCadProActionPerformed

    private void JmiExcProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiExcProActionPerformed
        // TODO add your handling code here:
        new Excluir_Produto().setVisible(true);
        dispose();
    }//GEN-LAST:event_JmiExcProActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new Relatorio_Mesa().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial_Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmiCadGar;
    private javax.swing.JMenuItem JmiCadPro;
    private javax.swing.JMenuItem JmiCalcComi;
    private javax.swing.JMenuItem JmiEdiGar;
    private javax.swing.JMenuItem JmiEdiPro;
    private javax.swing.JMenuItem JmiExcGar;
    private javax.swing.JMenuItem JmiExcPro;
    private javax.swing.JMenuItem JmiVisuGar;
    private javax.swing.JMenuItem JmiVisuPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
